spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=GMT%2B8
  profiles:
    active: dev



#  环境设置


mybatis-plus:
  global-config:
    db-config:
      id-type: auto

      logic-delete-value: 1
      logic-not-delete-value: 0